package nullable

// Do not modify. Generated by nullable-generate.

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

// Byte represents a byte value that may be null.
// This type implements the Scanner interface so it
// can be used as a scan destination, similar to NullString.
// It also implements the necessary interfaces to serialize
// to and from JSON.
type Byte struct {
	Byte  byte
	Valid bool
}

// ByteFromPtr returns a Byte whose value matches ptr.
func ByteFromPtr(ptr *byte) Byte {
	var v Byte
	return v.Assign(ptr)
}

// Assign the value of the pointer. If the pointer is nil,
// then then Valid is false, otherwise Valid is true.
func (n *Byte) Assign(ptr *byte) Byte {
	if ptr == nil {
		n.Valid = false
		n.Byte = 0
	} else {
		n.Valid = true
		n.Byte = *ptr
	}
	return *n
}

// Ptr returns a pointer to byte. If Valid is false
// then the pointer is nil, otherwise it is non-nil.
func (n Byte) Ptr() *byte {
	if n.Valid {
		v := n.Byte
		return &v
	}
	return nil
}

// Scan implements the sql.Scanner interface.
func (n *Byte) Scan(value interface{}) error {
	var nt sql.NullInt64
	err := nt.Scan(value)
	if err != nil {
		return err
	}
	n.Valid = nt.Valid
	n.Byte = byte(nt.Int64)
	return nil
}

// Value implements the driver.Valuer interface.
func (n Byte) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return int64(n.Byte), nil
}

// MarshalJSON implements the json.Marshaler interface.
func (n Byte) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return json.Marshal(n.Byte)
	}
	return []byte("null"), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (n *Byte) UnmarshalJSON(p []byte) error {
	if bytes.Equal(p, []byte("null")) {
		n.Byte = 0
		n.Valid = false
		return nil
	}

	var v byte
	if err := json.Unmarshal(p, &v); err != nil {
		return err
	}

	n.Byte = v
	n.Valid = true
	return nil
}
