package nullable

// Do not modify. Generated by nullable-generate.

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

// Float32 represents a float32 value that may be null.
// This type implements the Scanner interface so it
// can be used as a scan destination, similar to NullString.
// It also implements the necessary interfaces to serialize
// to and from JSON.
type Float32 struct {
	Float32 float32
	Valid   bool
}

// Float32FromPtr returns a Float32 whose value matches ptr.
func Float32FromPtr(ptr *float32) Float32 {
	var v Float32
	return v.Assign(ptr)
}

// Assign the value of the pointer. If the pointer is nil,
// then then Valid is false, otherwise Valid is true.
func (n *Float32) Assign(ptr *float32) Float32 {
	if ptr == nil {
		n.Valid = false
		n.Float32 = 0
	} else {
		n.Valid = true
		n.Float32 = *ptr
	}
	return *n
}

// Ptr returns a pointer to float32. If Valid is false
// then the pointer is nil, otherwise it is non-nil.
func (n Float32) Ptr() *float32 {
	if n.Valid {
		v := n.Float32
		return &v
	}
	return nil
}

// Normalized returns a Float32 that can be compared with
// another Float32 for equality.
func (n Float32) Normalized() Float32 {
	if n.Valid {
		return n
	}
	// If !Valid, then Float32 could be any value.
	// Normalized value can be compared for equality.
	return Float32{}
}

// Scan implements the sql.Scanner interface.
func (n *Float32) Scan(value interface{}) error {
	var nt sql.NullFloat64
	err := nt.Scan(value)
	if err != nil {
		return err
	}
	n.Valid = nt.Valid
	n.Float32 = float32(nt.Float64)
	return nil
}

// Value implements the driver.Valuer interface.
func (n Float32) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return float64(n.Float32), nil
}

// MarshalJSON implements the json.Marshaler interface.
func (n Float32) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return json.Marshal(n.Float32)
	}
	return []byte("null"), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (n *Float32) UnmarshalJSON(p []byte) error {
	if bytes.Equal(p, jsonNull) {
		n.Float32 = 0
		n.Valid = false
		return nil
	}

	var v float32
	if err := json.Unmarshal(p, &v); err != nil {
		return err
	}

	n.Float32 = v
	n.Valid = true
	return nil
}
