package nullable

// Do not modify. Generated by nullable-generate.

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

// Int represents an int value that may be null.
// This type implements the Scanner interface so it
// can be used as a scan destination, similar to NullString.
// It also implements the necessary interfaces to serialize
// to and from JSON.
type Int struct {
	Int   int
	Valid bool
}

// IntFromPtr returns a Int whose value matches ptr.
func IntFromPtr(ptr *int) Int {
	var v Int
	return v.Assign(ptr)
}

// Assign the value of the pointer. If the pointer is nil,
// then then Valid is false, otherwise Valid is true.
func (n *Int) Assign(ptr *int) Int {
	if ptr == nil {
		n.Valid = false
		n.Int = 0
	} else {
		n.Valid = true
		n.Int = *ptr
	}
	return *n
}

// Ptr returns a pointer to int. If Valid is false
// then the pointer is nil, otherwise it is non-nil.
func (n Int) Ptr() *int {
	if n.Valid {
		v := n.Int
		return &v
	}
	return nil
}

// Scan implements the sql.Scanner interface.
func (n *Int) Scan(value interface{}) error {
	var nt sql.NullInt64
	err := nt.Scan(value)
	if err != nil {
		return err
	}
	n.Valid = nt.Valid
	n.Int = int(nt.Int64)
	return nil
}

// Value implements the driver.Valuer interface.
func (n Int) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return int64(n.Int), nil
}

// MarshalJSON implements the json.Marshaler interface.
func (n Int) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return json.Marshal(n.Int)
	}
	return []byte("null"), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (n *Int) UnmarshalJSON(p []byte) error {
	if bytes.Equal(p, []byte("null")) {
		n.Int = 0
		n.Valid = false
		return nil
	}

	var v int
	if err := json.Unmarshal(p, &v); err != nil {
		return err
	}

	n.Int = v
	n.Valid = true
	return nil
}
