package nullable

// Do not modify. Generated by nullable-generate.

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

// Int64 represents an int64 value that may be null.
// This type implements the Scanner interface so it
// can be used as a scan destination, similar to NullString.
// It also implements the necessary interfaces to serialize
// to and from JSON.
type Int64 struct {
	Int64 int64
	Valid bool
}

// Int64FromPtr returns a Int64 whose value matches ptr.
func Int64FromPtr(ptr *int64) Int64 {
	var v Int64
	return v.Assign(ptr)
}

// Assign the value of the pointer. If the pointer is nil,
// then then Valid is false, otherwise Valid is true.
func (n *Int64) Assign(ptr *int64) Int64 {
	if ptr == nil {
		n.Valid = false
		n.Int64 = 0
	} else {
		n.Valid = true
		n.Int64 = *ptr
	}
	return *n
}

// Ptr returns a pointer to int64. If Valid is false
// then the pointer is nil, otherwise it is non-nil.
func (n Int64) Ptr() *int64 {
	if n.Valid {
		v := n.Int64
		return &v
	}
	return nil
}

// Scan implements the sql.Scanner interface.
func (n *Int64) Scan(value interface{}) error {
	var nt sql.NullInt64
	err := nt.Scan(value)
	if err != nil {
		return err
	}
	n.Valid = nt.Valid
	n.Int64 = nt.Int64

	return nil
}

// Value implements the driver.Valuer interface.
func (n Int64) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return int64(n.Int64), nil
}

// MarshalJSON implements the json.Marshaler interface.
func (n Int64) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return json.Marshal(n.Int64)
	}
	return []byte("null"), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (n *Int64) UnmarshalJSON(p []byte) error {
	if bytes.Equal(p, []byte("null")) {
		n.Int64 = 0
		n.Valid = false
		return nil
	}

	var v int64
	if err := json.Unmarshal(p, &v); err != nil {
		return err
	}

	n.Int64 = v
	n.Valid = true
	return nil
}
