package nullable

// Do not modify. Generated by nullable-generate.

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

// Int8 represents an int8 value that may be null.
// This type implements the Scanner interface so it
// can be used as a scan destination, similar to NullString.
// It also implements the necessary interfaces to serialize
// to and from JSON.
type Int8 struct {
	Int8  int8
	Valid bool
}

// Int8FromPtr returns a Int8 whose value matches ptr.
func Int8FromPtr(ptr *int8) Int8 {
	var v Int8
	return v.Assign(ptr)
}

// Assign the value of the pointer. If the pointer is nil,
// then then Valid is false, otherwise Valid is true.
func (n *Int8) Assign(ptr *int8) Int8 {
	if ptr == nil {
		n.Valid = false
		n.Int8 = 0
	} else {
		n.Valid = true
		n.Int8 = *ptr
	}
	return *n
}

// Ptr returns a pointer to int8. If Valid is false
// then the pointer is nil, otherwise it is non-nil.
func (n Int8) Ptr() *int8 {
	if n.Valid {
		v := n.Int8
		return &v
	}
	return nil
}

// Normalized returns an Int8 that can be compared with
// another Int8 for equality.
func (n Int8) Normalized() Int8 {
	if n.Valid {
		return n
	}
	// If !Valid, then Int8 could be any value.
	// Normalized value can be compared for equality.
	return Int8{}
}

// Scan implements the sql.Scanner interface.
func (n *Int8) Scan(value interface{}) error {
	var nt sql.NullInt64
	err := nt.Scan(value)
	if err != nil {
		return err
	}
	n.Valid = nt.Valid
	n.Int8 = int8(nt.Int64)
	return nil
}

// Value implements the driver.Valuer interface.
func (n Int8) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return int64(n.Int8), nil
}

// MarshalJSON implements the json.Marshaler interface.
func (n Int8) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return json.Marshal(n.Int8)
	}
	return []byte("null"), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (n *Int8) UnmarshalJSON(p []byte) error {
	if bytes.Equal(p, jsonNull) {
		n.Int8 = 0
		n.Valid = false
		return nil
	}

	var v int8
	if err := json.Unmarshal(p, &v); err != nil {
		return err
	}

	n.Int8 = v
	n.Valid = true
	return nil
}
