package nullable

// Do not modify. Generated by nullable-generate.

import (
	"bytes"
	"database/sql"
	"database/sql/driver"
	"encoding/json"
)

// Uint32 represents a uint32 value that may be null.
// This type implements the Scanner interface so it
// can be used as a scan destination, similar to NullString.
// It also implements the necessary interfaces to serialize
// to and from JSON.
type Uint32 struct {
	Uint32 uint32
	Valid  bool
}

// Assign the value of the pointer. If the pointer is nil,
// then then Valid is false, otherwise Valid is true.
func (n *Uint32) Assign(ptr *uint32) Uint32 {
	if ptr == nil {
		n.Valid = false
		n.Uint32 = 0
	} else {
		n.Valid = true
		n.Uint32 = *ptr
	}
	return *n
}

// Pointer returns a pointer to uint32. If Valid is false
// then the pointer is nil, otherwise it is non-nil.
func (n Uint32) Pointer() *uint32 {
	if n.Valid {
		v := n.Uint32
		return &v
	}
	return nil
}

// Scan implements the sql.Scanner interface.
func (n *Uint32) Scan(value interface{}) error {
	var nt sql.NullInt64
	err := nt.Scan(value)
	if err != nil {
		return err
	}
	n.Valid = nt.Valid
	n.Uint32 = uint32(nt.Int64)
	return nil
}

// Value implements the driver.Valuer interface.
func (n Uint32) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return int64(n.Uint32), nil
}

// MarshalJSON implements the json.Marshaler interface.
func (n Uint32) MarshalJSON() ([]byte, error) {
	if n.Valid {
		return json.Marshal(n.Uint32)
	}
	return []byte("null"), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface.
func (n *Uint32) UnmarshalJSON(p []byte) error {
	if bytes.Equal(p, []byte("null")) {
		n.Uint32 = 0
		n.Valid = false
		return nil
	}

	var v uint32
	if err := json.Unmarshal(p, &v); err != nil {
		return err
	}

	n.Uint32 = v
	n.Valid = true
	return nil
}
